### ISSUE TITLE
Add Language to Title metadata

### ISSUE THREAD

**Issue by ianweatherburn** [dvnlgls/GM-IMDb-Page-Cleaner#1]
In modifyLayout() function, I added the following code, to display the title language with the current title metadata
Not sure if you would consider adding it your very useful IMDB Page Cleaner TamperMonkey script. Thank you. Much appreciated.

  const titleMetadata = document.querySelectorAll(".ipc-page-section--baseAlt :first-child > .ipc-inline-list--show-dividers > :last-child")[0];
  const language = document.querySelectorAll(".ipc-metadata-list [data-testid='title-details-languages'] .ipc-inline-list__item .ipc-metadata-list-item__list-content-item--link")[0];

  // Add to the language to the title metadata
  if (titleMetadata) {
    if (language) {
      titleMetadata.after(" ・ " + language.innerHTML);
    }
  }

![CleanShot 2023-05-31 at 12 54 38@2x](https://github.com/dvnlgls/GM-IMDb-Page-Cleaner/assets/19514284/34c67912-bedb-4323-80e0-f06963fcaf58)

**Comment by dvnlgls** [comment]
@ianweatherburn Thanks for the appreciation. I'm glad to see someone find my little script useful. 

I'm also happy to see your suggestion be in line with the spirit of the script: to provide a foundation where people can add customization on top. Though I'm sure you find the language useful, I don't know if all the users actually prefer that. 

So this made me think of a compromise solution. Instead of declining your contribution, I'd like to add it to the script's GM page so that people who like it may use it. That is, if you're ok with that. 

I too have minor modifications of my own that I'd like to publish. For instance, I load all the user reviews (up to the default limit set by IMDb) in a scrollable section just beneath the header. Code if you're interested:

```
function loadAllReviews() {
  const userReviews = document.querySelectorAll("[data-testid='UserReviews']")[0];
  const currentUrl = userReviews.getElementsByClassName('ipc-title-link-wrapper')[0];
  const modifiedUrl = currentUrl.href.split('reviews?')[0] + 'reviews?sort=reviewVolume&dir=desc&ratingFilter=0';
  
  document.querySelectorAll("[data-testid='reviews-author']")[0].remove();
  
  
  fetch(modifiedUrl)
	.then((response) => {
    return response.text();  
	}).then((html) => {
		const parsedDoc = new DOMParser();
		const doc = parsedDoc.parseFromString(html, "text/html");
		return doc;
	})
	.then((doc) => {
    const newReviews = doc.getElementsByClassName('lister-list')[0].innerHTML;
    userReviews.getElementsByClassName('ipc-list-card--base')[0].innerHTML = newReviews;
    cleanReviewFooter();
	})
  .then((doc) => {
    cleanReviewFooter();
	});
  
  
}

function cleanReviewFooter() {
  const reviews = document.getElementsByClassName('lister-item-content');

  if(reviews.length > 0){
    const reviewArr = [...reviews];
    
    reviewArr.forEach(e => {
      let footer = e.getElementsByClassName('text-muted')[0];
      footer.innerText = footer.innerText.replace('|','');
    })
    
  }
}
```

**Comment by ianweatherburn** [comment]
Hey, thanks for replying.
I fully understand, and sure go ahead and make that code available to
whoever wants it. 🙂​

Interesting fun below. Will have a look at it.
Thanks again.
Ian

**Comment by dvnlgls** [comment]
Added a custom snippet section to the script's home page as promised. https://greasyfork.org/en/scripts/444255-imdb-page-cleaner
